# Dockerfile

# jdk17 Image Start
FROM openjdk:17
ARG DB_HOST
ARG DB_PORT
ARG DB_SCHEMA
ARG DB_USERNAME
ARG DB_PASSWORD
ARG JWT_SECRET
ARG FCM_APP_URL
ARG FCM_FILE_NAME
ARG S3_BUCKET_NAME
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG DYNAMODB_ENDPOINT
ARG DYNAMODB_REGION
ARG DYNAMODB_ACCESS_KEY
ARG DYNAMODB_SECRET_KEY
ARG S3_URL
ARG WEB_HOOK_URL
ARG LICENSE_BASE_URL
ARG LICENSE_API_KEY
ARG CLOUD_FRONT_URL
ARG WEB_HOOK_URL
ARG SMS_API_KEY
ARG SMS_SECRET_KEY
ARG SMS_PHONE_NUMBER
ARG SMS_DOMAIN
ARG NAVER_CLIENT_ID
ARG NAVER_REDIRECT_URL
ARG NAVER_CLIENT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URL
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_SECRET
ARG KAKAO_REDIRECT_URL
ARG ELASTIC_SEARCH_USERNAME
ARG ELASTIC_SEARCH_PASSWORD
ARG ELASTIC_SEARCH_URL

ENV DB_HOST=${DB_HOST} \
    DB_PORT=${DB_PORT} \
    DB_SCHEMA=${DB_SCHEMA} \
    DB_USERNAME=${DB_USERNAME} \
    DB_PASSWORD=${DB_PASSWORD} \
    JWT_SECRET=${JWT_SECRET} \
    FCM_APP_URL=${FCM_APP_URL} \
    S3_URL=${S3_URL} \
    S3_BUCKET_NAME=${S3_BUCKET_NAME} \
    S3_ACCESS_KEY=${S3_ACCESS_KEY} \
    S3_SECRET_KEY=${S3_SECRET_KEY} \
    DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT} \
    DYNAMODB_REGION=${DYNAMODB_REGION} \
    DYNAMODB_ACCESS_KEY=${DYNAMODB_ACCESS_KEY} \
    DYNAMODB_SECRET_KEY=${DYNAMODB_SECRET_KEY} \
    WEB_HOOK_URL=${WEB_HOOK_URL} \
    LICENSE_BASE_URL=${LICENSE_BASE_URL} \
    LICENSE_API_KEY=${LICENSE_API_KEY} \
    CLOUD_FRONT_URL=${CLOUD_FRONT_URL} \
    WEB_HOOK_URL=${WEB_HOOK_URL} \
    SMS_API_KEY=${SMS_API_KEY} \
    SMS_SECRET_KEY=${SMS_SECRET_KEY} \
    SMS_PHONE_NUMBER=${SMS_PHONE_NUMBER} \
    SMS_DOMAIN=${SMS_DOMAIN} \
    FCM_FILE_NAME=${FCM_FILE_NAME} \
    KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID} \
    KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET} \
    KAKAO_REDIRECT_URL=${KAKAO_REDIRECT_URL} \
    GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \
    GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \
    GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL} \
    NAVER_CLIENT_ID=${NAVER_CLIENT_ID} \
    NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET} \
    NAVER_REDIRECT_URL=${NAVER_REDIRECT_URL} \
    ELASTIC_SEARCH_URL=${ELASTIC_SEARCH_URL} \
    ELASTIC_SEARCH_USERNAME=${ELASTIC_SEARCH_USERNAME} \
    ELASTIC_SEARCH_PASSWORD=${ELASTIC_SEARCH_PASSWORD}

# 인자 설정 - JAR_File
ARG JAR_FILE=build/libs/*.jar

# jar 파일 복제
COPY ${JAR_FILE} app.jar

# 인자 설정 부분과 jar 파일 복제 부분 합쳐서 진행해도 무방
#COPY build/libs/*.jar app.jar

# 실행 명령어
ENTRYPOINT ["java", "-jar", "app.jar"]